"""empty message

Revision ID: dc28dc71489a
Revises: e3b31d6afa48
Create Date: 2025-07-14 14:16:03.558236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc28dc71489a'
down_revision = 'e3b31d6afa48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.alter_column('altura',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.alter_column('diametro',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('fecha_active',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('fecha_active',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.alter_column('diametro',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.alter_column('altura',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
