"""empty message

Revision ID: e3b31d6afa48
Revises: a5cffa318ac2
Create Date: 2025-07-14 13:49:42.769789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b31d6afa48'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('cualidad', sa.String(), nullable=False),
    sa.Column('color_de_ojos', sa.String(), nullable=False),
    sa.Column('altura', sa.Boolean(), nullable=False),
    sa.Column('color_de_cabello', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('caracteristicas', sa.String(), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=False),
    sa.Column('habitantes', sa.String(), nullable=False),
    sa.Column('diametro', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('apellido', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('fecha_active', sa.Boolean(), nullable=False))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('fecha_active')
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')

    op.drop_table('planetas')
    op.drop_table('personajes')
    # ### end Alembic commands ###
